export enum ErrorType {
    OutputTooShort = "OutputTooShort",
    OutputTooLong = "OutputTooLong",
    PwdTooShort = "PwdTooShort",
    PwdTooLong = "PwdTooLong",
    SaltTooShort = "SaltTooShort",
    SaltTooLong = "SaltTooLong",
    AdTooShort = "AdTooShort",
    AdTooLong = "AdTooLong",
    SecretTooShort = "SecretTooShort",
    SecretTooLong = "SecretTooLong",
    TimeTooSmall = "TimeTooSmall",
    TimeTooLarge = "TimeTooLarge",
    MemoryTooLittle = "MemoryTooLittle",
    MemoryTooMuch = "MemoryTooMuch",
    LanesTooFew = "LanesTooFew",
    LanesTooMany = "LanesTooMany",
    IncorrectType = "IncorrectType",
    IncorrectVersion = "IncorrectVersion",
    DecodingFail = "DecodingFail"
}
